apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio-prod
spec:
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: minio-port
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: minio-console
  type: NodePort # Use NodePort if LoadBalancer is not supported in your environment
